// Auto-generated by LibreLane
module mesh_tile(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input[5:0] TILE_ID,
  input clk,
  input rst,
  input boot_mode,
  input[10:0] boot_addr,
  input[7:0] boot_data,
  input boot_wen,
  input[35:0] north_in,
  input[35:0] south_in,
  input[35:0] east_in,
  input[35:0] west_in,
  output[35:0] north_out,
  output[35:0] south_out,
  output[35:0] east_out,
  output[35:0] west_out,
  input[35:0] ne_in,
  input[35:0] nw_in,
  input[35:0] se_in,
  input[35:0] sw_in,
  output[35:0] ne_out,
  output[35:0] nw_out,
  output[35:0] se_out,
  output[35:0] sw_out,
  input dft_mode,
  input dft_ce,
  input dft_we,
  input[10:0] dft_addr,
  input[7:0] dft_wdata,
  output[7:0] dft_rdata
);
endmodule
