meta:
  version: 3
  flow: Classic

DESIGN_NAME: mesh_tile
VERILOG_FILES:
  - dir::../../src/mesh - Psi&Aan/mesh_tile.v
  - dir::../../src/mesh - Psi&Aan/mesh_router.v
  - dir::../../src/serv/rtl/*.v 
  - dir::../../src/serv/servile/*.v
  - dir::../../src/subservient/rtl/sram2048x8_gf180.v
  - dir::../../src/subservient/rtl/subservient_core.v
  - dir::../../src/subservient/rtl/subservient_rf_ram_if.v


# What should the clock port be?
CLOCK_PORT: clk
CLOCK_PERIOD: 40

VDD_NETS:
  - VDD
GND_NETS:
  - VSS

FP_SIZING: absolute
DIE_AREA: [0, 0, 900, 750]
CORE_AREA: [10, 10, 890, 740]

PL_TARGET_DENSITY_PCT: 50

PDN_CORE_RING: False
PDN_ENABLE_PINS: True
PDN_VERTICAL_LAYER: Metal2
PDN_HORIZONTAL_LAYER: Metal3
PDN_VWIDTH: 2
PDN_HWIDTH: 2
PDN_VPITCH: 30
PDN_HPITCH: 30

MACROS:
  gf180mcu_ocd_ip_sram__sram1024x8m8wm1:
    gds:
      - dir::../../libs/gf180mcu_ocd_ip_sram/cells/gf180mcu_ocd_ip_sram__sram1024x8m8wm1/gf180mcu_ocd_ip_sram__sram1024x8m8wm1.gds
    lef:
      - dir::../../libs/gf180mcu_ocd_ip_sram/cells/gf180mcu_ocd_ip_sram__sram1024x8m8wm1/gf180mcu_ocd_ip_sram__sram1024x8m8wm1.lef
    vh:
      - dir::../../libs/gf180mcu_ocd_ip_sram/cells/gf180mcu_ocd_ip_sram__sram1024x8m8wm1/gf180mcu_ocd_ip_sram__sram1024x8m8wm1.blackbox.v
    lib:
      "*_tt_025C_3v30":
        - dir::../../libs/gf180mcu_ocd_ip_sram/cells/gf180mcu_ocd_ip_sram__sram1024x8m8wm1/gf180mcu_ocd_ip_sram__sram1024x8m8wm1__tt_025C_3v30.lib
      "*_ff_n40C_3v60":
        - dir::../../libs/gf180mcu_ocd_ip_sram/cells/gf180mcu_ocd_ip_sram__sram1024x8m8wm1/gf180mcu_ocd_ip_sram__sram1024x8m8wm1__ff_n40C_3v60.lib
    instances:
      sram2048.u_bank0:
        location: [15, 112]
        orientation: N
      sram2048.u_bank1:
        location: [330, 112]
        orientation: N 

PDN_MACRO_CONNECTIONS:
  - "sram2048.u_bank0 VDD VSS VDD VSS"
  - "sram2048.u_bank1 VDD VSS VDD VSS"

PDN_CFG: dir::pdn_cfg.tcl


# Don't error on DRC for the small block during development
ERROR_ON_MAGIC_DRC: False


