/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module gf180mcu_as_sc_mcu7t3v3__and2_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__and2_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao21_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao21_4(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao21b_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao21b_4(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao22_2(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao22_4(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao31_2(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__ao31_4(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi21_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi21_4(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi21b_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi21b_4(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi22_2(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi22_4(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi31_2(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__aoi31_4(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__buff_12(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__buff_2(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__buff_4(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__buff_8(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__clkbuff_12(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__clkbuff_4(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__clkbuff_8(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__dfsrtp_2(VPW, VNW, VDD, VSS, CLK, D, RN, SN, Q);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RN;
  wire RN;
  input SN;
  wire SN;
  output Q;
  wire Q;
endmodule

module gf180mcu_as_sc_mcu7t3v3__dfxtn_2(VPW, VNW, VDD, VSS, CLK, D, Q);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
endmodule

module gf180mcu_as_sc_mcu7t3v3__dfxtp_2(VPW, VNW, VDD, VSS, CLK, D, Q);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
endmodule

module gf180mcu_as_sc_mcu7t3v3__diode_2(VPW, VNW, VDD, VSS, DIODE);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input DIODE;
  wire DIODE;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fill_1(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fill_2(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fill_4(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fill_8(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fillcap_16(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fillcap_4(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__fillcap_8(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__inv_2(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__inv_4(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__inv_6(VPW, VNW, VDD, VSS, A, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__invz_2(VPW, VNW, VDD, VSS, A, EN, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input EN;
  wire EN;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__maj3_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__maj3_4(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__mux2_2(VPW, VNW, VDD, VSS, A, B, S, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__mux2_4(VPW, VNW, VDD, VSS, A, B, S, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand2_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand2_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand2b_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand2b_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand3_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nand4_2(VPW, VNW, VDD, VSS, A, B, C, D, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nor2_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nor2_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nor2b_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nor2b_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__nor3_2(VPW, VNW, VDD, VSS, A, B, C, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__or2_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__or2_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__tap_2(VPW, VNW, VDD, VSS);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
endmodule

module gf180mcu_as_sc_mcu7t3v3__tieh_4(VPW, VNW, VDD, VSS, ONE);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output ONE;
  wire ONE;
endmodule

module gf180mcu_as_sc_mcu7t3v3__tiel_4(VPW, VNW, VDD, VSS, ZERO);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output ZERO;
  wire ZERO;
endmodule

module gf180mcu_as_sc_mcu7t3v3__xnor2_2(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module gf180mcu_as_sc_mcu7t3v3__xnor2_4(VPW, VNW, VDD, VSS, A, B, Y);
  input VPW;
  wire VPW;
  input VNW;
  wire VNW;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule
